# Generated by Django 3.2.25 on 2025-08-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaikuanXlsxIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='索引ID')),
                ('billing_period', models.CharField(max_length=20, verbose_name='账期')),
                ('billing_category', models.CharField(max_length=50, verbose_name='账单大类')),
                ('business_category', models.CharField(max_length=50, verbose_name='业务大类')),
                ('business_subcategory', models.CharField(max_length=50, verbose_name='业务小类')),
                ('order_number', models.CharField(max_length=100, verbose_name='订单号')),
                ('sub_order_number', models.CharField(max_length=100, unique=True, verbose_name='子订单号')),
                ('order_time', models.DateTimeField(blank=True, null=True, verbose_name='下单时间')),
                ('delivery_time', models.DateTimeField(blank=True, null=True, verbose_name='确认收货时间')),
                ('product_id', models.CharField(max_length=50, verbose_name='商品ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='sku')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价（元）')),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单实际金额（元）')),
                ('refund_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='退款单号')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='退款金额（元）')),
                ('payment_channel', models.CharField(blank=True, max_length=50, null=True, verbose_name='收/付渠道')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='业务流水号')),
                ('merchant_order_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='商户订单号')),
                ('payment_time', models.DateTimeField(blank=True, null=True, verbose_name='打款时间')),
                ('payment_update_time', models.DateTimeField(blank=True, null=True, verbose_name='打款更新时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '贷款Excel索引',
                'verbose_name_plural': '贷款Excel索引管理',
                'db_table': 'daikuan_xlsx_index',
            },
        ),
    ]
