# Generated by Django 3.2.25 on 2025-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daikuanxlsxindex',
            name='sub_order_number',
            field=models.CharField(max_length=100, verbose_name='子订单号'),
        ),
    ]
