# Generated by Django 3.2.25 on 2025-08-08 08:11

import activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0003_commodity_commoditysituation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='活动图ID')),
                ('image', models.ImageField(upload_to=activity.models.activity_image_path, verbose_name='活动图片')),
                ('status', models.CharField(choices=[('online', '上线'), ('offline', '下线'), ('pending', '待上线')], default='pending', max_length=20, verbose_name='上线情况')),
                ('online_time', models.DateTimeField(blank=True, null=True, verbose_name='上线时间')),
                ('offline_time', models.DateTimeField(blank=True, null=True, verbose_name='下线时间')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='涉及类目')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('commodities', models.ManyToManyField(related_name='activity_images', to='commodity.Commodity', verbose_name='涉及商品')),
            ],
            options={
                'verbose_name': '活动图',
                'verbose_name_plural': '活动图',
                'db_table': 'Activity_Image',
            },
        ),
    ]
