# Generated by Django 3.2.25 on 2025-08-08 10:51

import activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        ('commodity', '0003_commodity_commoditysituation'),
    ]

    operations = [
        # 添加commodities多对多关系
        migrations.AddField(
            model_name='activityimage',
            name='commodities',
            field=models.ManyToManyField(related_name='activity_images', to='commodity.Commodity', verbose_name='涉及商品'),
        ),
    ]
