# Generated by Django 3.2.25 on 2025-08-11 06:48

import activity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20250808_1851'),
        ('commodity', '0003_commodity_commoditysituation'),
    ]

    operations = [
        # 创建活动图片与商品的多对多关系
        migrations.AddField(
            model_name='activityimage',
            name='commodities',
            field=models.ManyToManyField(related_name='activity_images', to='commodity.Commodity', verbose_name='涉及商品'),
        ),
    ]
