# Generated by Django 3.2.25 on 2025-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20250811_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityimage',
            name='commodities',
        ),
        migrations.AddField(
            model_name='activityimage',
            name='commodities',
            field=models.TextField(blank=True, help_text='多个商品编号用逗号分隔', null=True, verbose_name='涉及商品编号'),
        ),
    ]
