# Generated by Django 3.2.25 on 2025-08-13 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('openid', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信openid')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('nickname', models.CharField(max_length=100, verbose_name='用户昵称')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码')),
                ('default_receiver', models.CharField(blank=True, max_length=100, null=True, verbose_name='默认收货人昵称')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='默认收货省')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='市')),
                ('county', models.CharField(blank=True, max_length=50, null=True, verbose_name='县')),
                ('detailed_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认详细地址')),
                ('membership_level', models.IntegerField(default=0, verbose_name='用户等级')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='消费金额累计')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户信息',
                'db_table': 'users_user',
            },
        ),
    ]
