# Generated by Django 3.2.25 on 2025-08-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250813_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='微信openid'),
        ),
    ]
