# Generated by Django 3.2.25 on 2025-08-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_openid_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='user_avatars/', verbose_name='用户头像'),
        ),
    ]
