# Generated by Django 3.2.25 on 2025-08-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='address',
            name='receiver_name',
            field=models.CharField(default='', max_length=50, verbose_name='收货人'),
        ),
    ]
