services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
      - DEBUG=True
      - DB_ENGINE=django.db.backends.mysql
      - DB_HOST=rm-uf623nc5tc2icc2u9uo.mysql.rds.aliyuncs.com
      - DB_PORT=3306
      - DB_NAME=wechat_member
      - DB_USER=youlansy
      - DB_PASSWORD=Allblu2022#
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16