# Generated by Django 3.2.25 on 2025-06-24 07:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('style_code', models.CharField(blank=True, max_length=50, verbose_name='款式编码')),
                ('category', models.CharField(max_length=100, verbose_name='商品类目')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('image', models.ImageField(upload_to='commodities/', verbose_name='商品图')),
                ('promo_image', models.ImageField(blank=True, upload_to='promotions/', verbose_name='推广图')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='商品尺码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '商品数据',
                'verbose_name_plural': '商品数据',
                'db_table': 'Commodity_data',
            },
        ),
        migrations.CreateModel(
            name='CustomerServiceUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='用户昵称')),
                ('mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '客服用户',
                'verbose_name_plural': '客服用户',
                'db_table': 'Customer_service_user',
            },
        ),
        migrations.CreateModel(
            name='OperationUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('nickname', models.CharField(max_length=50, unique=True, verbose_name='用户昵称')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('level', models.IntegerField(choices=[(1, '普通客服'), (2, '高级管理员'), (3, '超级管理员')], default=1, verbose_name='用户等级')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '运营用户',
                'verbose_name_plural': '运营用户',
                'db_table': 'Operation_user',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='订单ID')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='收货人昵称')),
                ('province', models.CharField(max_length=50, verbose_name='收货省')),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('county', models.CharField(max_length=50, verbose_name='县')),
                ('detailed_address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('product_list', models.TextField(verbose_name='商品列表')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('shipped', '已发货'), ('delivered', '已送达'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'order_data',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$')], verbose_name='手机号')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '普通用户'), (2, 'VIP用户'), (3, '管理员')], default=1, verbose_name='用户等级')),
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='用户昵称')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='密码')),
                ('contact_number', models.CharField(max_length=20, verbose_name='联系电话')),
                ('default_receiver', models.CharField(max_length=100, verbose_name='默认收货人昵称')),
                ('province', models.CharField(max_length=50, verbose_name='默认收货省')),
                ('city', models.CharField(max_length=50, verbose_name='默认市')),
                ('county', models.CharField(max_length=50, verbose_name='县')),
                ('detailed_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='默认详细地址')),
                ('membership_level', models.IntegerField(default=0, verbose_name='用户等级')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('total_spending', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='消费金额累计')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户信息',
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='CommoditySituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', '上线'), ('offline', '下线'), ('pending', '待上线')], max_length=20, verbose_name='商品情况')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('online_time', models.DateTimeField(blank=True, null=True, verbose_name='上线时间')),
                ('offline_time', models.DateTimeField(blank=True, null=True, verbose_name='下架时间')),
                ('sales_volume', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.commodity', verbose_name='商品ID')),
            ],
            options={
                'verbose_name': '商品状态',
                'verbose_name_plural': '商品状态',
                'db_table': 'Commodity_Situation',
            },
        ),
    ]
