# Generated by Django 3.2.25 on 2025-06-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commodity',
        ),
        migrations.RemoveField(
            model_name='commoditysituation',
            name='commodity',
        ),
        migrations.DeleteModel(
            name='CustomerServiceUser',
        ),
        migrations.DeleteModel(
            name='OperationUser',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='CommoditySituation',
        ),
    ]
