# Generated by Django 3.2.25 on 2025-08-08 08:07

import commodity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0002_auto_20250626_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('commodity_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('style_code', models.CharField(blank=True, max_length=50, verbose_name='款式编码')),
                ('category', models.CharField(max_length=100, verbose_name='商品类目')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('image', models.ImageField(upload_to=commodity.models.commodity_image_path, verbose_name='商品图')),
                ('promo_image', models.ImageField(blank=True, upload_to='promotions/', verbose_name='推广图')),
                ('size', models.CharField(blank=True, max_length=50, verbose_name='商品尺码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '商品数据',
                'verbose_name_plural': '商品数据',
                'db_table': 'Commodity_data',
            },
        ),
        migrations.CreateModel(
            name='CommoditySituation',
            fields=[
                ('commodity_id', models.AutoField(primary_key=True, serialize=False, verbose_name='商品ID')),
                ('status', models.CharField(choices=[('online', '上线'), ('offline', '下线'), ('pending', '待上线')], max_length=20, verbose_name='商品情况')),
                ('online_time', models.DateTimeField(auto_now_add=True, verbose_name='上线时间')),
                ('offline_time', models.DateTimeField(auto_now_add=True, verbose_name='下架时间')),
                ('sales_volume', models.PositiveIntegerField(default=0, verbose_name='销量')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '商品状态',
                'verbose_name_plural': '商品状态',
                'db_table': 'Commodity_Situation',
            },
        ),
    ]
