# Generated by Django 3.2.25 on 2025-08-13 02:30

import commodity.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_commodity_commoditysituation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='image',
            field=models.ImageField(upload_to=commodity.models.commodity_image_path, verbose_name='商品主图'),
        ),
        migrations.CreateModel(
            name='CommodityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=commodity.models.commodity_multiple_images_path, verbose_name='商品图片')),
                ('is_main', models.BooleanField(default=False, verbose_name='是否为主图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='commodity.commodity', verbose_name='关联商品')),
            ],
            options={
                'verbose_name': '商品图片',
                'verbose_name_plural': '商品图片',
                'db_table': 'Commodity_Images',
            },
        ),
    ]
