# Generated by Django 3.2.25 on 2025-09-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_auto_20250813_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='category_detail',
            field=models.CharField(blank=True, max_length=100, verbose_name='商品分类'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='颜色'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='color_image',
            field=models.ImageField(blank=True, upload_to='color_images/', verbose_name='颜色对应图片'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='height',
            field=models.CharField(blank=True, max_length=50, verbose_name='身高范围'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='spec_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='规格编码'),
        ),
    ]
