# Generated by Django 3.2.25 on 2025-09-15 09:37

import commodity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_auto_20250915_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='color_image',
            field=models.ImageField(blank=True, upload_to=commodity.models.commodity_color_image_path, verbose_name='颜色对应图片'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='promo_image',
            field=models.ImageField(blank=True, upload_to=commodity.models.commodity_promo_image_path, verbose_name='推广图'),
        ),
    ]
