# Generated by Django 3.2.25 on 2025-09-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0006_auto_20250915_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commoditysituation',
            name='commodity_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='商品ID'),
        ),
    ]
