# Generated by Django 3.2.25 on 2025-09-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0007_alter_commoditysituation_commodity_id'),
    ]

    operations = [
        # 手动删除冲突的外键约束
        migrations.RunSQL(
            sql='ALTER TABLE `commodity_commoditysituation` DROP FOREIGN KEY `Commodity_Situation_commodity_id_c7b42ead_fk_Commodity`;',
            reverse_sql='',
        ),
    ]
