# Generated by Django 3.2.25 on 2025-09-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0008_auto_20250915_1741'),
    ]

    operations = [
        # 步骤1: 为Commodity表添加临时字符串字段
        migrations.RunSQL(
            sql='ALTER TABLE `Commodity_data` ADD COLUMN `temp_commodity_id` VARCHAR(100) NULL;',
            reverse_sql='ALTER TABLE `Commodity_data` DROP COLUMN `temp_commodity_id`;',
        ),
        
        # 步骤2: 将整数类型的commodity_id转换为字符串并复制到临时字段
        migrations.RunSQL(
            sql='UPDATE `Commodity_data` SET `temp_commodity_id` = CAST(`commodity_id` AS CHAR(100));',
            reverse_sql='',
        ),
        
        # 步骤3: 处理CommoditySituation表 - 删除外键约束（如果存在）
        migrations.RunSQL(
            sql='ALTER TABLE `Commodity_Situation` DROP FOREIGN KEY IF EXISTS `Commodity_Situation_commodity_id_c7b42ead_fk_Commodity`;',
            reverse_sql='',
        ),
        
        # 步骤4: 修改Commodity表的主键为字符串类型
        migrations.RunSQL(
            sql='ALTER TABLE `Commodity_data` DROP PRIMARY KEY, CHANGE COLUMN `commodity_id` `commodity_id_old` INT NULL, CHANGE COLUMN `temp_commodity_id` `commodity_id` VARCHAR(100) NOT NULL, ADD PRIMARY KEY (`commodity_id`);',
            reverse_sql='ALTER TABLE `Commodity_data` DROP PRIMARY KEY, CHANGE COLUMN `commodity_id` `temp_commodity_id` VARCHAR(100) NULL, CHANGE COLUMN `commodity_id_old` `commodity_id` INT NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (`commodity_id`);',
        ),
        
        # 步骤5: 为CommoditySituation表添加临时字符串字段
        migrations.RunSQL(
            sql='ALTER TABLE `Commodity_Situation` ADD COLUMN `temp_commodity_id` VARCHAR(100) NULL;',
            reverse_sql='ALTER TABLE `Commodity_Situation` DROP COLUMN `temp_commodity_id`;',
        ),
        
        # 步骤6: 更新CommoditySituation表的关联字段
        migrations.RunSQL(
            sql='UPDATE `Commodity_Situation` cs INNER JOIN `Commodity_data` c ON cs.commodity_id = c.commodity_id_old SET cs.temp_commodity_id = c.commodity_id;',
            reverse_sql='',
        ),
        
        # 步骤7: 修改CommoditySituation表的主键为字符串类型
        migrations.RunSQL(
            sql='ALTER TABLE `Commodity_Situation` DROP PRIMARY KEY, CHANGE COLUMN `commodity_id` `commodity_id_old` INT NULL, CHANGE COLUMN `temp_commodity_id` `commodity_id` VARCHAR(100) NOT NULL, ADD PRIMARY KEY (`commodity_id`);',
            reverse_sql='ALTER TABLE `Commodity_Situation` DROP PRIMARY KEY, CHANGE COLUMN `commodity_id` `temp_commodity_id` VARCHAR(100) NULL, CHANGE COLUMN `commodity_id_old` `commodity_id` INT NOT NULL AUTO_INCREMENT, ADD PRIMARY KEY (`commodity_id`);',
        ),
        
        # 步骤8: 清理旧字段
        migrations.RunSQL(
            sql='ALTER TABLE `Commodity_data` DROP COLUMN `commodity_id_old`;',
            reverse_sql='',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE `Commodity_Situation` DROP COLUMN `commodity_id_old`;',
            reverse_sql='',
        ),
        
        # 步骤9: 对于CommodityImage表，由于它使用外键关联，Django会自动处理类型转换
        # 这里不需要额外的SQL操作
    ]
