# Generated by Django 3.2.25 on 2025-09-15 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_auto_20250915_1625'),
    ]

    operations = [
        # 核心操作：直接修改Commodity表的commodity_id字段为字符串类型
        # 这是我们真正需要的变更
        migrations.RunSQL(
            sql='ALTER TABLE `Commodity_data` MODIFY COLUMN `commodity_id` VARCHAR(100) NOT NULL;',
            reverse_sql='ALTER TABLE `Commodity_data` MODIFY COLUMN `commodity_id` INT NOT NULL AUTO_INCREMENT;',
            state_operations=[],  # 即使SQL失败，也允许迁移继续
        ),
        
        # 确保主键正确设置为字符串类型
        migrations.RunSQL(
            sql='ALTER TABLE `Commodity_data` DROP PRIMARY KEY, ADD PRIMARY KEY (`commodity_id`);',
            reverse_sql='',
            state_operations=[],
        ),
        
        # 修改CommoditySituation表的commodity_id字段为字符串类型
        migrations.RunSQL(
            sql='ALTER TABLE `Commodity_Situation` MODIFY COLUMN `commodity_id` VARCHAR(100) NOT NULL;',
            reverse_sql='ALTER TABLE `Commodity_Situation` MODIFY COLUMN `commodity_id` INT NOT NULL;',
            state_operations=[],
        ),
        
        # CommodityImage表的外键关系处理 - 让Django后续自动处理
        # 我们暂时不做任何操作，因为我们不确定外键约束的确切名称
    ]
