# Generated by Django 3.2.25 on 2025-09-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0014_recreate_tables'),
    ]

    operations = [
    ]
