# Generated by Django 3.2.25 on 2025-09-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0015_fix_manual_table_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleCodeSituation',
            fields=[
                ('style_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='款式编码')),
                ('status', models.CharField(choices=[('online', '上线'), ('offline', '下线'), ('pending', '待上线')], max_length=20, verbose_name='款式状态')),
                ('online_time', models.DateTimeField(auto_now_add=True, verbose_name='上线时间')),
                ('offline_time', models.DateTimeField(blank=True, null=True, verbose_name='下架时间')),
                ('sync_data_count', models.PositiveIntegerField(default=0, verbose_name='同步数据量')),
            ],
            options={
                'verbose_name': '款式状态',
                'verbose_name_plural': '款式状态',
                'db_table': 'StyleCode_Situation',
            },
        ),
    ]
