# Generated by Django 3.2.25 on 2025-09-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0016_stylecodesituation'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoditysituation',
            name='style_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='款式编码'),
        ),
    ]
