# Generated by Django 3.2.25 on 2025-09-18 05:32

import commodity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0017_commoditysituation_style_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='StyleCodeData',
            fields=[
                ('style_code', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='款式编码')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('image', models.ImageField(upload_to=commodity.models.commodity_image_path, verbose_name='商品主图')),
                ('category', models.CharField(max_length=100, verbose_name='商品类目')),
                ('category_detail', models.CharField(blank=True, max_length=100, verbose_name='商品分类')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '款式数据',
                'verbose_name_plural': '款式数据',
                'db_table': 'StyleCode_Data',
            },
        ),
    ]
