# Generated by Django 3.2.25 on 2025-07-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP地址')),
                ('access_token', models.CharField(max_length=100, unique=True, verbose_name='访问令牌')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '访问令牌',
                'verbose_name_plural': '访问令牌',
                'db_table': 'access_token',
            },
        ),
    ]
