# Generated by Django 3.2.25 on 2025-07-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('register_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Customer_service_user',
            },
        ),
        migrations.CreateModel(
            name='OperationUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('register_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Operation_user',
            },
        ),
    ]
