# Generated by Django 3.2.25 on 2025-07-14 03:55

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('OperationUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerserviceuser',
            name='register_token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='operationuser',
            name='register_token',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
