# Generated by Django 3.2.25 on 2025-07-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationUser', '0002_add_register_token_field'),
    ]


