# Generated by Django 3.2.25 on 2025-07-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OperationUser', '0003_auto_20250714_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerserviceuser',
            name='user_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='operationuser',
            name='user_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
