# Generated by Django 3.2.25 on 2025-07-14 04:25

from django.db import migrations
from django.db import connection

def drop_column_if_exists(apps, schema_editor):
    # 检查并删除Customer_service_user表中的registration_date字段
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = 'Customer_service_user' AND COLUMN_NAME = 'registration_date'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE Customer_service_user DROP COLUMN registration_date;")

    # 检查并删除Operation_user表中的registration_date字段
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = 'Operation_user' AND COLUMN_NAME = 'registration_date'
        """)
        if cursor.fetchone():
            cursor.execute("ALTER TABLE Operation_user DROP COLUMN registration_date;")

def add_column_back(apps, schema_editor):
    # 恢复字段（迁移回滚时使用）
    with connection.cursor() as cursor:
        cursor.execute("ALTER TABLE Customer_service_user ADD COLUMN registration_date DATETIME;")
        cursor.execute("ALTER TABLE Operation_user ADD COLUMN registration_date DATETIME;")

class Migration(migrations.Migration):

    dependencies = [
        ('OperationUser', '0004_auto_20250714_1220'),
    ]

    operations = [
        migrations.RunPython(drop_column_if_exists, reverse_code=add_column_back)
    ]
