# Generated by Django 3.2.25 on 2025-08-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OperationUser', '0005_remove_registration_date_column'),
    ]

    operations = [
        # 暂时注释掉可能导致错误的删除操作
        # migrations.RemoveField(
        #     model_name='customerserviceuser',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='customerserviceuser',
        #     name='register_token',
        # ),
        # migrations.RemoveField(
        #     model_name='customerserviceuser',
        #     name='updated_at',
        # ),
        # migrations.RemoveField(
        #     model_name='operationuser',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='operationuser',
        #     name='register_token',
        # ),
        # migrations.RemoveField(
        #     model_name='operationuser',
        #     name='updated_at',
        # ),
    ]
