# Generated by Django 3.2.25 on 2025-08-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OperationUser', '0006_auto_20250814_1114'),
    ]

    operations = [
        # 暂时移除这些操作，因为字段可能已不存在
        # migrations.RemoveField(
        #     model_name='customerserviceuser',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='customerserviceuser',
        #     name='register_token',
        # ),
        # migrations.RemoveField(
        #     model_name='customerserviceuser',
        #     name='updated_at',
        # ),
        # migrations.RemoveField(
        #     model_name='operationuser',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='operationuser',
        #     name='register_token',
        # ),
        # migrations.RemoveField(
        #     model_name='operationuser',
        #     name='updated_at',
        # ),
    ]
