# Generated by Django 3.2.25 on 2025-06-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='订单ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='收货人昵称')),
                ('province', models.CharField(max_length=50, verbose_name='收货省')),
                ('city', models.CharField(max_length=50, verbose_name='市')),
                ('county', models.CharField(max_length=50, verbose_name='县')),
                ('detailed_address', models.CharField(max_length=255, verbose_name='详细地址')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('product_list', models.TextField(verbose_name='商品列表')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('shipped', '已发货'), ('delivered', '已送达'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
                'db_table': 'order_data',
            },
        ),
    ]
