# Generated by Django 3.2.25 on 2025-06-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=20, primary_key=True, verbose_name='订单ID'),
        ),
    ]
