# Generated by Django 3.2.25 on 2025-08-14 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('shipped', '已发货'), ('delivered', '已送达'), ('canceled', '已取消'), ('processing', '售后中')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
    ]
