# Generated by Django 3.2.25 on 2025-08-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='express_company',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='快递公司'),
        ),
        migrations.AddField(
            model_name='order',
            name='express_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='快递单号'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='收货人电话'),
        ),
    ]
