# Generated by Django 3.2.25 on 2025-08-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20250820_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='express_number',
            field=models.CharField(blank=True, help_text='支持字母和数字组合，如SF1234567890', max_length=50, null=True, verbose_name='快递单号'),
        ),
    ]
