# Generated by Django 3.2.25 on 2025-08-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_express_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='logistics_process',
            field=models.TextField(blank=True, help_text='存储物流跟踪信息，格式为JSON字符串：[{"time": "时间", "location": "位置", "description": "描述"}]', null=True, verbose_name='物流过程信息'),
        ),
    ]
